### ISSUE TITLE
let's encrypt cert ended on 30 september on software.verapdf.org

### ISSUE THREAD

**Issue by ShockwaveNN** [veraPDF/veraPDF.github.io#32]
https://software.verapdf.org/

![image](https://user-images.githubusercontent.com/668524/65862306-a5463a80-e376-11e9-89eb-e5eb182fa43e.png)

All broswers and command line tools like `wget` mark site as unsafe

**Comment by carlwilson** [comment]
Thanks @ShockwaveNN the cert update automated task has had a problem. The cert is now updated and I hope that automated renewal now works, but we will see later this month.
