### ISSUE TITLE
Link to verapdf-greenfield-1.14.2-installer.zip return 404

### ISSUE THREAD

**Issue by ShockwaveNN** [veraPDF/veraPDF.github.io#33]
Steps:
1. Open https://software.verapdf.org/releases/1.14
2. Click on `verapdf-greenfield-1.14.2-installer.zip`
![image](https://user-images.githubusercontent.com/668524/68385979-1a721000-016c-11ea-9998-32533e5b8ae8.png)

This link worked at least 29 days ago

**Comment by bdoubrov** [comment]
This link was replaced by the link to version 1.14.8: https://software.verapdf.org/releases/1.14/verapdf-greenfield-1.14.8-installer.zip. Version 1.14.2 had issues with signatures of Java packages. Please use ithe new one instead of your link to version 1.14.2

**Comment by ShockwaveNN** [comment]
@bdoubrov Yep, I figure out that I should try to use new version, but I think it's not good to get 404 from direct link on your site, maybe add info about it on https://software.verapdf.org/releases/1.14 and remove links to 1.14.2 altogether?

**Comment by carlwilson** [comment]
Hi @ShockwaveNN I've removed the broken links and will close this. I've opened another issue here: https://github.com/veraPDF/veraPDF-library/issues/1045 to remind us to add some kind of detection to pick these issues up earlier.

**Comment by ShockwaveNN** [comment]
@carlwilson Seems good to me, thanks :)
